/*
 * Generates public/places-ttmap.js from the community live map's data files.
 *
 * These are real, exact in-game coordinates — businesses, garages and self
 * storage — rather than the map-derived estimates in data.js. Source:
 *   https://github.com/supernovaplus/ttmap  (data by glitchdetector)
 *
 *   node scripts/fetch-places.mjs
 */

import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const base = 'https://raw.githubusercontent.com/supernovaplus/ttmap/master/data';

/** Which of their datasets we take, and how each maps onto our categories. */
const SOURCES = [
  {
    file: 'bizBlips.json',
    prefix: 'biz',
    category: (v) => guessBusinessCategory(v.name),
    describe: (v) => [v.perks?.join(', '), v.price && `Price ${v.price}`]
      .filter(Boolean).join(' · ') || 'Business'
  },
  {
    file: 'garageBlips.json',
    prefix: 'gar',
    category: () => 'vehicle',
    describe: (v) => [v.type, v.spawns && `Spawns: ${v.spawns}`].filter(Boolean).join(' · ')
  },
  {
    file: 'ssBlips.json',
    prefix: 'ss',
    category: () => 'work',
    describe: (v) => [v.capacity && `Capacity ${v.capacity}`, v.fee && `Fee ${v.fee}`]
      .filter(Boolean).join(' · ')
  }
];

/* Business names carry their own type — sort them into our filter chips. */
function guessBusinessCategory(name = '') {
  const n = name.toLowerCase();
  if (/airport|hangar|aircraft|airfield|aviation/.test(n)) return 'airport';
  if (/dock|marina|harbour|harbor|boat|pier|ferry/.test(n)) return 'dock';
  if (/train|yard|quarry|mill|mine|logging|sawmill|refinery|plant|factory|farm|export|storage/.test(n)) return 'work';
  if (/market|store|shop|mart|pizza|burger|cafe|bar|club|casino/.test(n)) return 'market';
  if (/bank|atm|loan/.test(n)) return 'money';
  if (/garage|customs|mechanic|repair|tune/.test(n)) return 'vehicle';
  return 'hq';
}

const slug = (s) => s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '').slice(0, 40);

const out = [];
const seen = new Set();

for (const source of SOURCES) {
  const res = await fetch(`${base}/${source.file}`);
  if (!res.ok) {
    console.error(`Failed to fetch ${source.file}: HTTP ${res.status}`);
    process.exit(1);
  }
  const data = await res.json();
  let n = 0;

  for (const [key, value] of Object.entries(data)) {
    const x = Number(value.coordinates?.x);
    const y = Number(value.coordinates?.y);
    if (!Number.isFinite(x) || !Number.isFinite(y)) continue;

    let id = `${source.prefix}-${slug(value.name || key)}`;
    while (seen.has(id)) id += '2';
    seen.add(id);

    out.push({
      id,
      n: value.name || key,
      c: source.category(value),
      x: Math.round(x),
      y: Math.round(y),
      p: 'exact',
      d: source.describe(value)
    });
    n++;
  }
  console.log(`${source.file}: ${n} places`);
}

out.sort((a, b) => a.n.localeCompare(b.n));

const body = out.map((p) =>
  `  { id: ${JSON.stringify(p.id)}, n: ${JSON.stringify(p.n)}, c: ${JSON.stringify(p.c)}, ` +
  `x: ${p.x}, y: ${p.y}, p: 'exact', d: ${JSON.stringify(p.d)} }`
).join(',\n');

writeFileSync(join(root, 'public', 'places-ttmap.js'),
`/*
 * GENERATED by scripts/fetch-places.mjs — do not edit by hand.
 *
 * Exact in-game coordinates for Transport Tycoon businesses, garages and self
 * storage, taken from the community live map at https://ttmap.eu
 *   project: https://github.com/supernovaplus/ttmap (by Nova+)
 *   data:    glitchdetector
 *
 * Unlike the estimates in data.js these are the real positions the server uses,
 * so they ship badged VERIFIED.
 */

export const TTMAP_PLACES = [
${body}
];
`);

console.log(`\nWrote public/places-ttmap.js — ${out.length} verified places.`);
